version: 1
builder:
  configs:
  - documentation_targets:
    - Identity Backend
    - Identity Frontend
    - Identity Shared
    - Identity Views
    - Identity Consumer
    - Identity Provider
    - Identity Standalone
